### PR TITLE
Update & optimize AssemblyScript

### PR DESCRIPTION
**Pull request by MaxGraey**
Suggest some minor refactoring and tweaks which could potentially speedup your algorithm.  Unfortunately hard to tell how this correct without tests so let me know if you find some issues

### CODE REVIEW

**Comment by johnSamilin** [comment]
Hey @MaxGraey thanks for the tweaks, it seems like it's faster a bit now

**Comment by MaxGraey** [comment]
> Hey @MaxGraey thanks for the tweaks, it seems like it's faster a bit now

Great! Just wondering how much faster?

**Comment by johnSamilin** [comment]
Now it consumes like 30 MB RAM instead of 48 and takes 66ms to find the path instead of 291ms

**Comment by MaxGraey** [comment]
Thanks) 4.4x speedup is not "faster a bit now" it's pretty nice boost in my opinion

**Comment by johnSamilin** [comment]
For sure! I just commented before I saw actual comparison

**Pull request merged**
